[package]
name = "garbled-circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5.1"
tokio = { workspace = true, features = [
    "rt",
    "sync",
    "macros",
    "rt-multi-thread",
] }
[features]
test-support = ["sl-mpc-mate/simple-relay"]

[[bench]]
name = "gc_garble_bench"
harness = false

[[bench]]
name = "gc_eval_bench"
harness = false

[dependencies]
aes = "0.8.4"
regex = "1.11.1"
rand = "0.8"
rand_chacha = "0.3"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.131"
aes-gcm = "0.10.3"
tokio = { version = "1.24.1" }
sl-mpc-mate = { git = "https://github.com/silence-laboratories/sl-crypto.git", rev = "804ae2b" }
sl-messages = { git = "https://github.com/silence-laboratories/sl-crypto.git", rev = "804ae2b" }
sha2 = "0.10.8"
merlin = "3.0.0"
signature = { version = "2.2.0" }
crypto-bigint = "0.6.1"
sl-compute-common = { git = "https://github.com/silence-laboratories/sl-crypto.git", branch = "sl-compute-common" }
bytemuck = { version = "1.22", features = [
    "derive",
    "min_const_generics",
    "extern_crate_alloc",
] }
thiserror = "1.0"

[workspace.dependencies]
tokio = "1.43.0"


[workspace]
members = [
    ".",
    "crates/hd-migration",
]