[package]
name = "garbled-circuit"
version = "1.3.1-pre.2"
edition = "2021"
license-file = "LICENSE"
rust-version = "1.88"
readme = "README.md"
publish = [ "sl" ]
include = [
  "/benches",
  "/circuits",
  "/src/",
  "/build.rs",
]

[features]
test-support = []
circuit-blake2b = []
circuit-sha512  = []

[[bench]]
name = "gc_garble_bench"
harness = false

[[bench]]
name = "gc_eval_bench"
harness = false

[dependencies]
sl-compute-common = { workspace = true }
sl-messages = { workspace = true }

aes = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
generic-array = { workspace = true }
sha2 = { workspace = true }
signature = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"
merlin = "3.0.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }


[workspace.dependencies]
aes = "0.8.4"
derivation-path = "0.2.0"
ff = "0.13.0"
generic-array = { version = "=0.14.7" }
group = "0.13.0"
hmac = { version = "0.12.1" }
k256 = { version = "0.13", default-features = false }
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.10.8"
signature = { version = "2.2.0" }
thiserror = "1.0"
tokio = "1.43.0"

garbled-circuit = { path = "./", version = "1.3.1-pre.1", registry = "sl" }
sl-secret-sharing = { path = "./crates/sl-secret-sharing", version = "0.1.0-pre.1", registry = "sl" }

sl-compute-common = { version = "1.1.0" }
sl-messages = { version = "1.3.0-pre.1", features = ["setup"] }

[workspace]
members = [
    ".",
    "crates/hd-migration",
    "crates/sl-secret-sharing",
    "crates/zcash",
]
