[package]
name = "hd-migration"
version = "0.1.0"
edition = "2024"


[dependencies]
garbled-circuit = { path = "../.." }

sl-mpc-mate = { git = "https://github.com/silence-laboratories/sl-crypto.git", rev = "804ae2b" }
sl-messages = { git = "https://github.com/silence-laboratories/sl-crypto.git", rev = "804ae2b" }
sl-compute-common = { git = "https://github.com/silence-laboratories/sl-crypto.git", branch = "sl-compute-common" }

# curve25519-dalek = { version = "4.1.3", features = ["precomputed-tables"]}
derivation-path = "0.2.0"
group = "0.13.0"
hmac = { version = "0.12.1" }
k256 = { version = "0.13", features = ["arithmetic"] }
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.10.8"
signature = { version = "2.2.0" }
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }


[features]
test-support = ["sl-mpc-mate/simple-relay"]
