[package]
name = "zcash"
version = "0.1.0-pre.3"
edition = "2024"
license-file = "../../LICENSE"
rust-version = "1.88"
publish = [ "sl" ]
include = [
  "/benches",
  "/src/",
]


[dependencies]
ff = { workspace = true }
garbled-circuit = { workspace = true, features = ["circuit-blake2b"] }
group = { workspace = true }
hmac = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }
sha2 = { workspace = true }
sl-compute-common = { workspace = true }
sl-messages = { workspace = true }
sl-secret-sharing = { workspace = true }

hex = "0.4"
pasta_curves = "0.5.1"

[dev-dependencies]
ciborium = "0.2"
blake2b_simd = "1.0.4"
criterion = "0.5.1"
hex = "0.4"
orchard = "0.13.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
garbled-circuit = { workspace = true, features = ["test-support"] }

[[bench]]
name = "blake2b_bench"
harness = false

[features]
session = ["dep:serde", "rand_chacha/serde1"]
test-support = []
