[package]
name = "zcash"
version = "0.1.0-pre.1"
edition = "2024"
license-file = "../../LICENSE"
rust-version = "1.88"
publish = [ "sl" ]


[dependencies]
ff = { workspace = true }
garbled-circuit = { workspace = true, features = ["circuit-blake2b"] }
group = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
sl-compute-common = { workspace = true }
sl-messages = { workspace = true }

hex = "0.4"
pasta_curves = "0.5.1"

[dev-dependencies]
blake2b_simd = "1.0.4"
criterion = "0.5.1"
hex = "0.4"
rand = { workspace = true }
rand_chacha = "0.3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "blake2b_bench"
harness = false

[features]
test-support = []
