name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  lints:
    name: Lints
    runs-on: github-builder
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all --workspace --locked -- -D warnings

  build-and-test:
    name: Rust tests
    runs-on: github-builder
    needs: lints
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo test --tests --all --release --locked

      - run: cargo test --tests -p zcash --release --locked -F dkg
